version: "3"
services:
  jscfe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - JSCCURRENT=.
        - JSCMODE=none
    image: jscdroiddev/jscfe
    ports:
      - "8080:80"
    depends_on:
      - jscbe
  jscbe:
    build:
      context: ./be
      dockerfile: Dockerfile
      args:
        - JSCCURRENT=.
    image: jscdroiddev/jscbe
    ports:
      - "9001:9001"
    depends_on:
      - jscdb
    volumes:
      - "./conf:/opt/jscbe/conf"
  jscdb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jscdb
      MYSQL_USER: jscdb
      MYSQL_PASSWORD: jscdb
    volumes:
      - "./db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
