version: '3'
services:
  jscfe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    image: jscdroiddev/jscfe
    ports:
      - "80:80"
  jscbe:
    build:
      context: .
      dockerfile: Dockerfile-be
    image: jscdroiddev/jscbe
    ports:
      - "8080:8080"
