version: '3.1'
services:
  jscfe:
    image: jscdroiddev/jscfe:latest
    ports:
      - "8080:80"
    depends_on:
      - jscbe
  jscbe:
    image: jscdroiddev/jscbe:latest
    ports:
      - "9001:9001"
    depends_on:
      - jscdb
    volumes:
      - "./conf:/opt/jscbe/conf"
  jscdb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jscdb
      MYSQL_USER: jscdb
      MYSQL_PASSWORD: jscdb
    volumes:
      - "./db/data:/var/lib/mysql"
    expose:
      - "3306"
